import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `serwist build` (see serwist.config.mjs) — a minified,
    // esbuild-bundled service worker, not source to lint.
    "public/sw.js",
    "public/sw.js.map",
    // Generated by `npm run build:offline-shell` (see package.json) — a minified,
    // esbuild-bundled offline recipe viewer, not source to lint.
    "public/offline-recipe.js",
    "public/offline-recipe.js.map",
    // The Expo mobile app is a separate project with its own lint setup (`expo lint`,
    // run from mobile/) — the web config shouldn't reach into it. Same boundary as
    // tsconfig.json's "exclude".
    "mobile/**",
    // Playwright's own generated output (npm run test:e2e), not source to lint.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
